server:
  port: ${PORT:8080}

spring:
  application:
    name: Learnin prep
  mail:
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mail:
      enabled: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://learnin-prep.vercel.app}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  frontend:
    url: ${FRONTEND_URL:https://learnin-prep.vercel.app} # Used for generating reset links

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESS_EXP_MS:900000}        # 15 minutes
    refresh-token-expiration-ms: ${JWT_REFRESH_EXP_MS:604800000}   # 7 days
    issuer: javaprep-backend

  admin:
    bootstrap-password: ${ADMIN_BOOTSTRAP_PASSWORD}
    bootstrap-email: ${ADMIN_BOOTSTRAP_EMAIL}

logging:
  level:
    com.javaprep.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG:
